### ISSUE TITLE
Login rate limit

### ISSUE THREAD

**Issue by lucas-marx** [n3s7or/symfonycasts-scraper#12]
Tried to login on the symfonycasts website and got this error 

> Login rate limit hit. If you are a self-aware (i.e. a real person), please message us: hello@symfonycasts.com

Anyone had the same problem? every time I get the links via scraper it's like a new login? how can I get around that?

**Comment by n3s7or** [comment]
It seems you have been doing lots of login requests to the symfonycasts site (as expected if you wanted to scrape the videos). 

> every time I get the links via scraper it's like a new login?

Yes, every new course you start scraping creates a new login (my bad).

>  how can I get around that?

For now you should wait until you are able to log in again, as usual, to your account. Then schedule scraping tasks.

The faster fix for this problem is to save the session object into a file/database/etc and reuse it until is valid:
https://github.com/n3s7or/symfonycasts-scraper/blob/3dd89a646cbb8cf5bba3de638183c1edf8aa2869/sycs/requestshelper.py#L17 

I will fix it today as soon as possible when out of my job. You're welcome to do a pull requests!

**Comment by lucas-marx** [comment]
okay, thanks again!
